from pathlib import Path

source = Path('tools/apply_030_camera.py').read_text()
old = '''old = \'\'\'        byPlayer.remove(session.playerId(), session);\n        byVessel.remove(session.vesselId(), session);\n        cancelTasks(session);\n\n        Mob vessel = session.vessel();\n\'\'\'\nnew = \'\'\'        byPlayer.remove(session.playerId(), session);\n        byVessel.remove(session.vesselId(), session);\n        cancelTasks(session);\n\n        if (player.isInsideVehicle()) {\n            player.leaveVehicle();\n        }\n        session.cameraTeleportInProgress(false);\n        session.cameraTransport(CameraTransport.NONE);\n\n        Mob vessel = session.vessel();\n\'\'\'\n# This exact block should occur only in releaseOnControllerDeath because quit has visibility line.\nif text.count(old) != 1:\n    raise SystemExit(f\'death camera anchor mismatch: {text.count(old)}\')\ntext = text.replace(old, new, 1)\n'''
new = '''death_start = text.index(\'    public void releaseOnControllerDeath(Player player) {\')\ndeath_end = text.index(\'    public void onPlayerRespawn(Player player) {\', death_start)\ndeath = text[death_start:death_end]\nold = \'\'\'        byPlayer.remove(session.playerId(), session);\n        byVessel.remove(session.vesselId(), session);\n        cancelTasks(session);\n\n        Mob vessel = session.vessel();\n\'\'\'\nnew = \'\'\'        byPlayer.remove(session.playerId(), session);\n        byVessel.remove(session.vesselId(), session);\n        cancelTasks(session);\n\n        if (player.isInsideVehicle()) {\n            player.leaveVehicle();\n        }\n        session.cameraTeleportInProgress(false);\n        session.cameraTransport(CameraTransport.NONE);\n\n        Mob vessel = session.vessel();\n\'\'\'\nif death.count(old) != 1:\n    raise SystemExit(f\'death camera anchor mismatch in method: {death.count(old)}\')\ndeath = death.replace(old, new, 1)\ntext = text[:death_start] + death + text[death_end:]\n'''
if source.count(old) != 1:
    raise SystemExit('could not rewrite old camera patch death section')
source = source.replace(old, new, 1)
exec(compile(source, 'apply_030_camera.py', 'exec'))
